ALTER TABLE suscriber ADD delivery_adress INT DEFAULT NULL;
ALTER TABLE suscriber ADD CONSTRAINT FK_B0995892C7440455 FOREIGN KEY (client) REFERENCES client (id);
ALTER TABLE suscriber ADD CONSTRAINT FK_B099589242FD3E30 FOREIGN KEY (delivery_adress) REFERENCES delivery_adress (id);