<?php

namespace AppBundle\Repository;

/**
 * ArticleStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleStockRepository extends \Doctrine\ORM\EntityRepository
{
}
