<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

	/**
     * Get the list rayons
     *
     * @return category collection
     */
    public function getRayonsList()
    {
       $q = $this->_em->createQueryBuilder('c');
                $q->select('c')
                ->from('AppBundle:Category','c')
                ->where('c.parent = c.id')
                ->orderBy('c.catname', 'ASC')
            ;
        

        return $q->getQuery()->getResult();
    }

    /**
     * Get the list category
     *
     * @return category collection
     */
    public function getCategoryList()
    {
       $q = $this->_em->createQueryBuilder('c');
                $q->select('c')
                ->from('AppBundle:Category','c')
                ->where('c.parent != c.id')
                ->orderBy('c.catname', 'ASC')
            ;
        

        return $q->getQuery()->getResult();
    }
}
