<?php

namespace AppBundle\Repository;

/**
 * DeliveryAdressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryAdressRepository extends \Doctrine\ORM\EntityRepository
{
}
