<?php

namespace AppBundle\Repository;

/**
 * DureeLivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DureeLivraisonRepository extends \Doctrine\ORM\EntityRepository
{
}
