<?php

namespace AppBundle\Repository;

/**
 * InventaireArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventaireArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
