<?php

namespace AppBundle\Repository;


use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * InventaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventaireRepository extends \Doctrine\ORM\EntityRepository
{

    public function getInventaires($currentPage=1)
    {
    	// $query = $this->_em->createQueryBuilder()
			  //           ->select('i', 'i.dateDeb')
			  //           ->from('AppBundle:Inventaire','i')
			  //            ->orderBy('i.dateDeb','asc');

    	$query = $this->createQueryBuilder('i')
    				  ->orderBy('i.id','desc')	;

	    $paginator = $this->paginate($query, $currentPage);

	    return $paginator;                     
    }

	public function paginate($dql, $page = 1, $limit = 10)
	{
	    $paginator = new Paginator($dql);

	    $paginator->getQuery()
		        ->setFirstResult($limit * ($page - 1)) // Offset
		        ->setMaxResults($limit); // Limit

	    return $paginator;
	}

    public function countInventaires()
    {
		$v =$this->createQueryBuilder('i')
                 ->getQuery()
        	     ->getResult();

		return count($v);
    }
}
