<?php

namespace AppBundle\Repository;

/**
 * LigneProformatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneProformatRepository extends \Doctrine\ORM\EntityRepository
{
}
