<?php

namespace AppBundle\Repository;

/**
 * LigneVenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneVenteRepository extends \Doctrine\ORM\EntityRepository
{
}
