<?php

namespace AppBundle\Repository;

/**
 * MotifSortieStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotifSortieStockRepository extends \Doctrine\ORM\EntityRepository
{
}
