<?php

namespace AppBundle\Repository;

/**
 * MvtStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MvtStockRepository extends \Doctrine\ORM\EntityRepository
{
}
