<?php

namespace AppBundle\Repository;

/**
 * ProformatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProformatRepository extends \Doctrine\ORM\EntityRepository
{
}
