<?php

namespace AppBundle\Repository;

/**
 * ServiceLogistiqueMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceLogistiqueMailRepository extends \Doctrine\ORM\EntityRepository
{
}
