<?php

namespace AppBundle\Repository;

/**
 * SortieStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SortieStockRepository extends \Doctrine\ORM\EntityRepository
{
}
