<?php

namespace AppBundle\Repository;

/**
 * SuscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuscriberRepository extends \Doctrine\ORM\EntityRepository
{
}
