<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TypeArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeArticleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get the paginated list of published articles
     *
     * @param int $page
     * @param int $maxperpage
     * @param string $sortby
     * @return Paginator
     */
    public function getListByCat($page=1, $maxperpage=10, $cat)
    {
        if($cat->getId() == $cat->getParent()->getId()){
            $q = $this->_em->createQueryBuilder('a');
                $q->select('a')
                ->from('AppBundle:TypeArticle','a')
                ->join('a.category' , 'c')
                ->where('c.parent = :cat')
                ->setParameter('cat', $cat->getId())
            ;
        }
        else{
            $q = $this->_em->createQueryBuilder('a');
                $q->select('a')
                ->from('AppBundle:TypeArticle','a')
                ->where('a.category = :cat')
                ->setParameter('cat', $cat->getId())
            ;
        }

        $q->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage)
            // ->orderBy('a.designation', 'ASC')
            ;

        return new Paginator($q);
    }

    /**
     * Get the paginated list of published articles
     *
     * @param int $page
     * @param int $maxperpage
     * @param string $sortby
     * @return Paginator
     */
    public function getList($page=1, $maxperpage=10)
    {
        $q = $this->_em->createQueryBuilder('a');
            $q->select('a')
            ->from('AppBundle:TypeArticle','a')
        ;

        $q->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage)
            // ->orderBy('a.designation', 'ASC')
            ;

        return new Paginator($q);
    }

    public function countArticlesTotal(){
    	$q = $this->_em->createQueryBuilder()
            ->select('article')
            ->from('AppBundle:TypeArticle','article')
        ;
        return count($q->getQuery()->getResult());
    }
}
