<?php

namespace AppBundle\Repository;

/**
 * ValFeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValFeatureRepository extends \Doctrine\ORM\EntityRepository
{
}
