#FOS User
# fos_user:
#     db_driver: orm
#     firewall_name: main
#     user_class: UserBundle\Entity\User

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
        address: lucas.dumont@stardustmultimedia.com
        sender_name: Lucas Dumont
    service:
        mailer: mailer
    